SIDE_BAR_HOME_BUTTON_NAME = "Home"
SIDE_BAR_CHARACTER_SHEET_BUTTON_NAME = "Character sheet"
SIDE_BAR_RULES_BUTTON_NAME = "Rules"


SIDE_BAR_BUTTONS_BACKGROUND_COLOR = "#bc0c0c"
SIDE_BAR_BUTTONS_TEXT_COLOR = "#ffffff"
SIDE_BAR_BUTTONS_HOOVER_BACKGROUND_COLOR = "#e82420"

# SIDE_BAR_BUTTONS_PRESSED_BACKGROUND_COLOR = "#ffffff"
# SIDE_BAR_BUTTONS_PRESSED_TEXT_COLOR = "#0c0c0c"


BIG_FONT_SIZE = "24px"
MEDIUM_FONT_SIZE = "16px"
SMALL_FONT_SIZE = "12px"